version: '3.9'
services:
  
  easybnb_easy_bnb_db:
    container_name: easybnb_easy_bnb_db
    hostname: easybnb_easy_bnb_db
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_DB_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_DB_HOST
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    command: [ "postgres", "-c", "max_prepared_transactions=200" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      timeout: 2s
      retries: 15

  easybnb_easy_bnb_service:
    container_name: easybnb_easy_bnb_service
    working_dir: /code/src
    command: uvicorn --log-level debug app.asgi:app --host $APP_HOST --port $APP_PORT --reload
    build: .
    depends_on:
      easybnb_easy_bnb_db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - POSTGRES_DB_LOGIN
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_HOST=easybnb_easy_bnb_db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME
      - SQLALCHEMY_ECHO
      - SQLALCHEMY_POOL_SIZE
      - LOGGING_LEVEL
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./src:/code/src
